galaxy_info:
  author: Julian-Samuel Gebühr
  company: mash
  role_name: borgbackup_server
  namespace: mash
  description: borgbackup_server
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - "7"
  license: AGPL-3.0-or-later
  min_ansible_version: '2.1'
